run:
  modules-download-mode: readonly
  timeout: 5m
issues:
  exclude-files:
    - "benchmark_test.go"
linters:
  enable:
    - gofmt
    - goimports
    - govet
    - goconst
    - gocritic
    - gocyclo
    - prealloc
    - unconvert
    - unparam
