name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.21]
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Run Tests
        run: go test -v -cover -covermode=count -coverprofile=coverage.out ./...

      - name: Convert Coverage
        uses: jandelgado/gcov2lcov-action@v1.0.9

      - name: Coveralls
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Sources
        uses: actions/checkout@master

      - name: Setup
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
